# Generated by Django 4.1.2 on 2022-10-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0011_logentry_serialized_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'view'), (1, 'create'), (2, 'update'), (3, 'delete')], db_index=True, verbose_name='action'),
        ),
    ]
